name: Bay SFCC Dev Deployment

 #Controls when the workflow will run
on:
   workflow_dispatch:
#on:
#  schedule:
#    - cron: "*/15 * * * *"
jobs:
  CHECK-FOR-NEW-COMMITS:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      commits: ${{ steps.check-new-commits.outputs.new_commits }}
      
    steps:
      - name: Checkout SFCC repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}
          #fetch-depth: '0'
          token: ${{ secrets.PACKAGE_TOKEN }}
          
      - name: Check for new commits in last 15 mins
        id: check-new-commits
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install git -y
          git log --since="15.minutes" --pretty=format:'"%s","%an","%ar","%h"'
          git log --oneline --reverse refs/heads/main | awk 'NR % 1 == 0'
